// Generated by scripts/generate-roleplay-artifact-identity.mjs.
// Do not edit this file by hand.
export const ROLEPLAY_EDGE_ARTIFACT_MANIFESTS = {
  "chat": {
    "schemaVersion": 1,
    "artifactName": "chat",
    "generatedFromRevision": null,
    "sourceDigest": "c7552c5d5207703291adcbd206b4da07f89044074b5e602176e5b653046f627f",
    "sourceFiles": [
      {
        "path": "supabase/functions/chat/index.ts",
        "sha256": "f092e0fd50fd41aefbfa91d487ddb109040cbea6453cf1b7c1bfa15ec9243d74"
      },
      {
        "path": "supabase/functions/_shared/admin-debug.ts",
        "sha256": "9e3e5beabe565d040ae0dae1e389ad9c66fd50aa78605433559894d66a9cc335"
      },
      {
        "path": "supabase/functions/_shared/xai-responses.ts",
        "sha256": "d2d1312e7f281263f101b051b8677d64c3d23e13b9afc57ed5f08301ac8c48e9"
      }
    ],
    "terminalMigration": "20260719001853_b7174d69-8075-443a-a464-6da9a10d50df.sql",
    "contractVersions": {
      "responseJob": "roleplay-response-job-v1",
      "selectedSourcePacket": "roleplay-source-packet-v1",
      "supportReviewEnvelope": "roleplay-support-review-envelope-v2",
      "reviewExport": "roleplay-review-export-v1",
      "fixtureSuite": "roleplay-regression-fixture-v1"
    }
  },
  "extract-memory-events": {
    "schemaVersion": 1,
    "artifactName": "extract-memory-events",
    "generatedFromRevision": null,
    "sourceDigest": "d76d72c4d2ad17a9be04a4967ac546105e7f7b3a739143d92c87c7ba1e934bce",
    "sourceFiles": [
      {
        "path": "supabase/functions/extract-memory-events/index.ts",
        "sha256": "78d652681822ea0d9cadd8dae678817156ac525570f3700ea1a1ce5fb27c9758"
      },
      {
        "path": "supabase/functions/_shared/admin-debug.ts",
        "sha256": "9e3e5beabe565d040ae0dae1e389ad9c66fd50aa78605433559894d66a9cc335"
      },
      {
        "path": "supabase/functions/_shared/xai-responses.ts",
        "sha256": "d2d1312e7f281263f101b051b8677d64c3d23e13b9afc57ed5f08301ac8c48e9"
      }
    ],
    "terminalMigration": "20260719001853_b7174d69-8075-443a-a464-6da9a10d50df.sql",
    "contractVersions": {
      "responseJob": "roleplay-response-job-v1",
      "selectedSourcePacket": "roleplay-source-packet-v1",
      "supportReviewEnvelope": "roleplay-support-review-envelope-v2",
      "reviewExport": "roleplay-review-export-v1",
      "fixtureSuite": "roleplay-regression-fixture-v1"
    }
  },
  "extract-character-updates": {
    "schemaVersion": 1,
    "artifactName": "extract-character-updates",
    "generatedFromRevision": null,
    "sourceDigest": "30f11375bc3cbc4ed06a86726b0905afdcbb6fbfab45c812e68ff6cd39afda36",
    "sourceFiles": [
      {
        "path": "supabase/functions/extract-character-updates/index.ts",
        "sha256": "24222a76225e923195fbbd03d0062315a445c6f6737f1089a89b00b5394b35ca"
      },
      {
        "path": "supabase/functions/_shared/admin-debug.ts",
        "sha256": "9e3e5beabe565d040ae0dae1e389ad9c66fd50aa78605433559894d66a9cc335"
      },
      {
        "path": "supabase/functions/_shared/xai-responses.ts",
        "sha256": "d2d1312e7f281263f101b051b8677d64c3d23e13b9afc57ed5f08301ac8c48e9"
      }
    ],
    "terminalMigration": "20260719001853_b7174d69-8075-443a-a464-6da9a10d50df.sql",
    "contractVersions": {
      "responseJob": "roleplay-response-job-v1",
      "selectedSourcePacket": "roleplay-source-packet-v1",
      "supportReviewEnvelope": "roleplay-support-review-envelope-v2",
      "reviewExport": "roleplay-review-export-v1",
      "fixtureSuite": "roleplay-regression-fixture-v1"
    }
  },
  "evaluate-goal-progress": {
    "schemaVersion": 1,
    "artifactName": "evaluate-goal-progress",
    "generatedFromRevision": null,
    "sourceDigest": "9a7c9f91767f5861daa00d55c38bb6f1aa4536ec0a238096f3a3501ac1b78e10",
    "sourceFiles": [
      {
        "path": "supabase/functions/evaluate-goal-progress/index.ts",
        "sha256": "0a846c1815f9f7c1c8e0b076ad98a0ea8c131a9a5f80878e93e3c0b00b2c486b"
      },
      {
        "path": "supabase/functions/_shared/admin-debug.ts",
        "sha256": "9e3e5beabe565d040ae0dae1e389ad9c66fd50aa78605433559894d66a9cc335"
      },
      {
        "path": "supabase/functions/_shared/xai-responses.ts",
        "sha256": "d2d1312e7f281263f101b051b8677d64c3d23e13b9afc57ed5f08301ac8c48e9"
      }
    ],
    "terminalMigration": "20260719001853_b7174d69-8075-443a-a464-6da9a10d50df.sql",
    "contractVersions": {
      "responseJob": "roleplay-response-job-v1",
      "selectedSourcePacket": "roleplay-source-packet-v1",
      "supportReviewEnvelope": "roleplay-support-review-envelope-v2",
      "reviewExport": "roleplay-review-export-v1",
      "fixtureSuite": "roleplay-regression-fixture-v1"
    }
  },
  "evaluate-goal-alignment": {
    "schemaVersion": 1,
    "artifactName": "evaluate-goal-alignment",
    "generatedFromRevision": null,
    "sourceDigest": "80352f050d3f9de7f7c150c8ee29047ccda51ebdbb992422338d39446245977a",
    "sourceFiles": [
      {
        "path": "supabase/functions/evaluate-goal-alignment/index.ts",
        "sha256": "8c44aa594a484321d0251adc74bd1ec4f617c0c331399603294d8021a0f58774"
      },
      {
        "path": "supabase/functions/_shared/admin-debug.ts",
        "sha256": "9e3e5beabe565d040ae0dae1e389ad9c66fd50aa78605433559894d66a9cc335"
      },
      {
        "path": "supabase/functions/_shared/xai-responses.ts",
        "sha256": "d2d1312e7f281263f101b051b8677d64c3d23e13b9afc57ed5f08301ac8c48e9"
      }
    ],
    "terminalMigration": "20260719001853_b7174d69-8075-443a-a464-6da9a10d50df.sql",
    "contractVersions": {
      "responseJob": "roleplay-response-job-v1",
      "selectedSourcePacket": "roleplay-source-packet-v1",
      "supportReviewEnvelope": "roleplay-support-review-envelope-v2",
      "reviewExport": "roleplay-review-export-v1",
      "fixtureSuite": "roleplay-regression-fixture-v1"
    }
  },
  "compress-day-memories": {
    "schemaVersion": 1,
    "artifactName": "compress-day-memories",
    "generatedFromRevision": null,
    "sourceDigest": "f7db53ab92ad9ef75aab1127f09a9c7e81499e4de05ca667c0c6a2c6d8fb1228",
    "sourceFiles": [
      {
        "path": "supabase/functions/compress-day-memories/index.ts",
        "sha256": "8f915019c9075b7de28650f4a55050968774d3238381fffc65a09a4f6db813a6"
      },
      {
        "path": "supabase/functions/_shared/admin-debug.ts",
        "sha256": "9e3e5beabe565d040ae0dae1e389ad9c66fd50aa78605433559894d66a9cc335"
      },
      {
        "path": "supabase/functions/_shared/xai-responses.ts",
        "sha256": "d2d1312e7f281263f101b051b8677d64c3d23e13b9afc57ed5f08301ac8c48e9"
      }
    ],
    "terminalMigration": "20260719001853_b7174d69-8075-443a-a464-6da9a10d50df.sql",
    "contractVersions": {
      "responseJob": "roleplay-response-job-v1",
      "selectedSourcePacket": "roleplay-source-packet-v1",
      "supportReviewEnvelope": "roleplay-support-review-envelope-v2",
      "reviewExport": "roleplay-review-export-v1",
      "fixtureSuite": "roleplay-regression-fixture-v1"
    }
  }
} as const;
