
DROP TRIGGER IF EXISTS update_conversation_dialog_debug_comments_updated_at
ON public.conversation_dialog_debug_comments;

CREATE TRIGGER update_conversation_dialog_debug_comments_updated_at
BEFORE UPDATE ON public.conversation_dialog_debug_comments
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();
