CREATE TABLE IF NOT EXISTS public.conversation_state_change_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL, conversation_id UUID NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE, source_message_id UUID NOT NULL REFERENCES public.messages(id) ON DELETE CASCADE, source_generation_id UUID NOT NULL, entity_type TEXT NOT NULL CHECK (entity_type IN ('character', 'side_character', 'world', 'story_goal', 'memory')), entity_id TEXT, entity_name TEXT, field_path TEXT NOT NULL, previous_value_preview TEXT, next_value_preview TEXT, story_day INTEGER, time_of_day TEXT, change_summary TEXT, call_type TEXT NOT NULL DEFAULT 'post_turn_state_sync', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_conversation_state_change_events_user ON public.conversation_state_change_events (user_id);
CREATE INDEX IF NOT EXISTS idx_conversation_state_change_events_source ON public.conversation_state_change_events (conversation_id, source_message_id, source_generation_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversation_state_change_events_entity ON public.conversation_state_change_events (conversation_id, entity_type, entity_id, created_at DESC);
ALTER TABLE public.conversation_state_change_events ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'conversation_state_change_events' AND policyname = 'Users can view own conversation state change events') THEN CREATE POLICY "Users can view own conversation state change events" ON public.conversation_state_change_events FOR SELECT USING ((SELECT auth.uid()) = user_id); END IF; IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'conversation_state_change_events' AND policyname = 'Users can insert own conversation state change events') THEN CREATE POLICY "Users can insert own conversation state change events" ON public.conversation_state_change_events FOR INSERT WITH CHECK ((SELECT auth.uid()) = user_id); END IF; IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'conversation_state_change_events' AND policyname = 'Users can delete own conversation state change events') THEN CREATE POLICY "Users can delete own conversation state change events" ON public.conversation_state_change_events FOR DELETE USING ((SELECT auth.uid()) = user_id); END IF; END $$;

CREATE TABLE IF NOT EXISTS public.conversation_world_state_snapshots (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL, conversation_id UUID NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE, source_message_id UUID NOT NULL REFERENCES public.messages(id) ON DELETE CASCADE, source_generation_id UUID NOT NULL, snapshot JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE (conversation_id, source_message_id, source_generation_id));
CREATE INDEX IF NOT EXISTS idx_conversation_world_state_snapshots_user ON public.conversation_world_state_snapshots (user_id);
CREATE INDEX IF NOT EXISTS idx_conversation_world_state_snapshots_conversation ON public.conversation_world_state_snapshots (conversation_id, source_message_id, source_generation_id);
ALTER TABLE public.conversation_world_state_snapshots ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'conversation_world_state_snapshots' AND policyname = 'Users can view own conversation world state snapshots') THEN CREATE POLICY "Users can view own conversation world state snapshots" ON public.conversation_world_state_snapshots FOR SELECT USING ((SELECT auth.uid()) = user_id); END IF; IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'conversation_world_state_snapshots' AND policyname = 'Users can insert own conversation world state snapshots') THEN CREATE POLICY "Users can insert own conversation world state snapshots" ON public.conversation_world_state_snapshots FOR INSERT WITH CHECK ((SELECT auth.uid()) = user_id); END IF; IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'conversation_world_state_snapshots' AND policyname = 'Users can update own conversation world state snapshots') THEN CREATE POLICY "Users can update own conversation world state snapshots" ON public.conversation_world_state_snapshots FOR UPDATE USING ((SELECT auth.uid()) = user_id) WITH CHECK ((SELECT auth.uid()) = user_id); END IF; IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'conversation_world_state_snapshots' AND policyname = 'Users can delete own conversation world state snapshots') THEN CREATE POLICY "Users can delete own conversation world state snapshots" ON public.conversation_world_state_snapshots FOR DELETE USING ((SELECT auth.uid()) = user_id); END IF; END $$;
DROP TRIGGER IF EXISTS update_conversation_world_state_snapshots_updated_at ON public.conversation_world_state_snapshots;
CREATE TRIGGER update_conversation_world_state_snapshots_updated_at BEFORE UPDATE ON public.conversation_world_state_snapshots FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE IF NOT EXISTS public.conversation_api_call_traces (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL, conversation_id UUID NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE, source_message_id UUID REFERENCES public.messages(id) ON DELETE CASCADE, source_generation_id UUID, call_type TEXT NOT NULL CHECK (call_type IN ('api_call_1_generation', 'post_turn_state_sync', 'memory_extraction', 'world_state_sync', 'side_character_generation', 'avatar_prompt_generation')), status TEXT NOT NULL DEFAULT 'ok' CHECK (status IN ('ok', 'skipped', 'error')), request_payload JSONB, response_payload JSONB, parsed_output JSONB, applied_changes JSONB, error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_conversation_api_call_traces_user ON public.conversation_api_call_traces (user_id);
CREATE INDEX IF NOT EXISTS idx_conversation_api_call_traces_source ON public.conversation_api_call_traces (conversation_id, source_message_id, source_generation_id, call_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversation_api_call_traces_conversation ON public.conversation_api_call_traces (conversation_id, created_at DESC);
ALTER TABLE public.conversation_api_call_traces ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'conversation_api_call_traces' AND policyname = 'Users can view own conversation api call traces') THEN CREATE POLICY "Users can view own conversation api call traces" ON public.conversation_api_call_traces FOR SELECT USING ((SELECT auth.uid()) = user_id); END IF; IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'conversation_api_call_traces' AND policyname = 'Users can insert own conversation api call traces') THEN CREATE POLICY "Users can insert own conversation api call traces" ON public.conversation_api_call_traces FOR INSERT WITH CHECK ((SELECT auth.uid()) = user_id); END IF; IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'conversation_api_call_traces' AND policyname = 'Users can delete own conversation api call traces') THEN CREATE POLICY "Users can delete own conversation api call traces" ON public.conversation_api_call_traces FOR DELETE USING ((SELECT auth.uid()) = user_id); END IF; END $$;