import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  apiInspectorPromptDocumentList,
  apiInspectorPromptDocuments,
  type ApiInspectorPromptDocumentId,
} from "./api-inspector-prompt-documents";

const requiredDocumentIds: ApiInspectorPromptDocumentId[] = ["api-call-1", "api-call-2-support"];

describe("api-inspector prompt document registry", () => {
  it("exposes exactly the two roleplay prompt review documents used by the header buttons", () => {
    expect(apiInspectorPromptDocumentList.map((document) => document.id)).toEqual(requiredDocumentIds);
    expect(Object.keys(apiInspectorPromptDocuments).sort()).toEqual([...requiredDocumentIds].sort());
  });

  it("keeps active review surfaces free of removed hidden-style-repair wording", () => {
    const activeSourceTruth = [
      "src/data/api-inspector-guide-phases.ts",
      "src/data/api-inspector-guide-template.ts",
      "src/data/api-inspector-code-truth-registry.ts",
      "src/data/api-inspector-live-map.ts",
      "src/pages/style-guide/app-architecture.tsx",
    ].map((path) => readFileSync(path, "utf8")).join("\n\n");

    [
      "Repair Pass",
      "one hidden retry",
      "injects a narrow one-turn correction",
      "optional style directive",
      "emits bounded guidance",
      "current-scene snapshot",
      "optional one-turn adaptive or repair text",
      "adaptive style guidance",
      "short corrective instruction",
      "gets injected",
      "one-time instruction",
      "ADAPTIVE STYLE DIRECTIVE",
    ].forEach((stalePhrase) => {
      expect(activeSourceTruth).not.toContain(stalePhrase);
    });
  });

  it("keeps API Call 1 documented as source-backed current prompt text", () => {
    const document = apiInspectorPromptDocuments["api-call-1"];

    expect(document.buttonLabel).toBe("API Call 1");
    expect(document.body).toContain("FULL SYSTEM MESSAGE GENERATED BY getSystemInstruction()");
    expect(document.body).toContain("GROK REQUEST BODY SENT BY CHAT EDGE FUNCTION");
    expect(document.body).toContain("BROWSER -> SUPABASE EDGE HEADERS");
    expect(document.body).toContain("EDGE -> xAI RESPONSES HEADERS");
    expect(document.body).toContain("REQUEST POLICY NOTES");
    expect(document.body).toContain("top_p is not currently sent by Chronicle");
    expect(document.body).toContain("store:false");
    expect(document.body).toContain('reasoning.effort:"medium"');
    expect(document.body).toContain('"providerTransport": "responses"');
    expect(document.body).toContain('"store": false');
    expect(document.body).toContain('"reasoning": { "effort": "medium" }');
    expect(document.body).toContain('"max_output_tokens": "{{1024 concise | 2048 balanced | 3072 detailed}}"');
    expect(document.body).not.toContain("GROK REQUEST BODY SENT BY CHAT EDGE FUNCTION\n{\n  \"model\": \"grok-4.3\",\n  \"messages\"");
    expect(document.body).toContain("CONTENT-REDIRECT FALLBACK BRANCH");
    expect(document.body).toContain("If the retry is also blocked, the edge function returns a structured content-filter notice over HTTP 200");
    expect(document.body).toContain("STREAMING DOUBLE-BLOCK EDGE EVENTS");
    expect(document.body).toContain("NON-STREAM DOUBLE-BLOCK EDGE RESPONSE");
    expect(document.body).toContain("chronicle_content_filter");
    expect(document.body).toContain("STREAMING PROVIDER-ERROR EDGE EVENTS");
    expect(document.body).toContain("chronicle_provider_error");
    expect(document.body).toContain('localNotice="provider_error"');
    expect(document.body).toContain("NON-STREAM PROVIDER-ERROR EDGE RESPONSE");
    expect(document.body).toContain('"error_type": "provider_response_parse_error | provider_http_error"');
    expect(document.body).toContain("Local notice messages are not included in later API Call 1 history.");
    expect(document.body).toContain('"temperature": 0.6');
    expect(document.body).toContain("{{up to 5 prior roleplay messages before the current turn; local notices excluded}}");
    expect(document.body).not.toContain("9-message API Call 1 history cap");
    expect(document.body).not.toContain("{{up to 9 prior roleplay messages");
    expect(document.body).toContain("{{compact current day/time, active scene, one character location/position roster, and capped current-day memory anchors}}");
    expect(document.body).not.toContain("{{optional one-turn adaptive style, detailed-collapse, or repair directive}}");
    expect(document.body).toContain("{{executionBrief}}");
    expect(document.body).toContain("RESPONSE DETAIL RULES ARE PART OF THE SYSTEM MESSAGE, NOT REPEATED IN THE FINAL USER MESSAGE");
    expect(document.body).toContain("NSFW INTENSITY RULES ARE PART OF THE SYSTEM MESSAGE, NOT REPEATED IN THE FINAL USER MESSAGE");
    expect(document.body).toContain("FINAL USER MESSAGE STRUCTURE SENT TO xAI");
    expect(document.body).toContain("[APP TURN CONTROLS]");
    expect(document.body).toContain("[PLAYER TURN]");
    expect(document.body).toContain('"content": "[APP TURN CONTROLS]\\n{{optional session counter}}');
    expect(document.body).toContain('{{optional regeneration request}}\\n\\n{{executionBrief}}\\n\\n[PLAYER TURN]\\n{{latest user text OR continue instruction wrapper}}');
    expect(document.body).toContain("EXECUTION BRIEF APPENDED INSIDE [APP TURN CONTROLS] ON EVERY LIVE ROLEPLAY CALL");
    expect(document.body).toContain("Continue from the latest established scene change.");
    expect(document.body).toContain("Recent messages provide story state and continuity, not a template for response length or structure.");
    expect(document.body).toContain("Follow the active Response Detail setting.");
    expect(document.body).toContain("Develop the AI-controlled character's side of the current exchange before stopping for the user");
    expect(document.body).toContain("User control is about authorship, not contact.");
    expect(document.body).toContain("Continue from after the latest visible assistant response.");
    expect(document.body).toContain("BACKGROUND USER-AUTHORED SCENE TURN FOR FACTS AND USER-CONTROL BOUNDARIES ONLY");
    expect(document.body).toContain("Develop the AI-controlled character's side of the current exchange enough that it follows the active RESPONSE DETAIL setting");
    expect(document.body).toContain("HIDDEN STYLE-REPAIR RETRY REMOVED FROM LIVE API CALL 1");
    expect(document.body).toContain("The first completed draft is committed unless the provider request itself fails.");
    expect(document.body).toContain("LOCAL STYLE DETECTOR TELEMETRY (DEBUG EXPORT ONLY, NOT SENT TO GROK)");
    expect(document.body).toContain("local://assistant-style-telemetry");
    expect(document.body).not.toContain("The draft needs revision because:");
    expect(document.body).toContain("--- SECTION 1 - CORE ROLE LOGIC ---");
    expect(document.body).toContain("--- SECTION 7 - DIALOG FORMATTING AND ROLEPLAY RULES ---");
	    expect(document.body).toContain("REGENERATION REQUEST APPENDED TO FINAL USER MESSAGE ONLY WHEN REGENERATING");
	    expect(document.body).toContain("Change the execution rather than the situation");
	    expect(document.body).toContain("CURRENT TURN STATE INSIDE [APP TURN CONTROLS]");
	    expect(document.body).toContain("Use this as the active scene anchor.");
	    expect(document.body).toContain("PREVIOUS ASSISTANT RESPONSE BEING REGENERATED");
	    expect(document.body).not.toContain("STYLE ADJUSTMENT AND DETAILED-COLLAPSE DIRECTIVES APPENDED ONLY WHEN RUNTIME DETECTORS TRIGGER");
	    expect(document.body).toContain("CONTINUE REQUEST FINAL USER MESSAGE ONLY WHEN PRESSING CONTINUE");
    expect(document.body).toContain("--- SECTION 8 - CHAT SETTINGS PER USER PREFERENCE ---");
    expect(document.body).toContain("This review document shows every possible chat-setting injection branch grouped under its setting.");
    expect(document.body).toContain("A real API Call 1 request sends only one branch per group based on the user's current chat settings.");
    expect(document.body).toContain("NARRATIVE POV: First Person");
    expect(document.body).toContain("NARRATIVE POV: Third Person");
    expect(document.body).toContain("NSFW INTENSITY: Normal");
    expect(document.body).toContain("NSFW INTENSITY: High");
    expect(document.body).not.toContain("NSFW INTENSITY: Natural");
    expect(document.body).toContain("RESPONSE DETAIL: Concise");
    expect(document.body).toContain("RESPONSE DETAIL / DEVELOPMENT LEVEL");
    expect(document.body).toContain("REQUEST max_tokens: 1024");
    expect(document.body).toContain("RESPONSE DETAIL: Balanced");
    expect(document.body).toContain("REQUEST max_tokens: 2048");
    expect(document.body).toContain("RESPONSE DETAIL: Detailed");
    expect(document.body).toContain("REQUEST max_tokens: 3072");
    expect(document.body).toContain("The final user message does not append a separate active NSFW context reminder.");
    expect(document.body).toContain("REALISM MODE: Off");
    expect(document.body).toContain("REALISM MODE: On");
    expect(document.body).not.toContain("{{first-person branch text}}");
    expect(document.body).not.toContain("not a literal payload dump");
    expect(document.body).not.toContain("forwardProgressRules");
    expect(document.body).not.toContain("verbosityRules");
    expect(document.body).not.toContain("realismRules");
    expect(document.body).not.toContain("traitAdherence");
  });

  it("covers API Call 2 support lanes with current prompt bodies", () => {
    const document = apiInspectorPromptDocuments["api-call-2-support"];

    expect(document.buttonLabel).toBe("API Call 2 + Support Calls");
    expect(document.body).toContain("API CALL 2: CHARACTER STATE SYNC");
    expect(document.body).toContain("BROWSER -> SUPABASE EDGE HEADERS");
    expect(document.body).toContain('"eligibleCharacters": "{{speaker/mention-filtered character names}}"');
    expect(document.body).toContain('"recentContext": "{{up to 10 recent roleplay messages for continuity/conflict checking}}"');
    expect(document.body).toContain("EDGE -> xAI RESPONSES HEADERS");
    expect(document.body).toContain("EDGE -> xAI CHAT COMPLETIONS HEADERS");
    expect(document.body).toContain("REQUEST POLICY NOTES");
	    expect(document.body).toContain("top_p is not currently sent by Chronicle");
	    expect(document.body).toContain('text.format.type = "json_schema"');
	    expect(document.body).toContain('"text": {');
    expect(document.body).toContain('"format": {');
    expect(document.body).toContain('"store": false');
    expect(document.body).toContain('"reasoning": { "effort": "medium" }');
    expect(document.body.match(/"stream": false/g)?.length).toBeGreaterThanOrEqual(5);
    expect(document.body).toContain('"chronicle_character_updates"');
	    expect(document.body).toContain("403 SAFE METADATA RETRY");
    expect(document.body).toContain("The fallback still uses structured output, but it is deliberately restricted to non-explicit metadata");
    expect(document.body).toContain("primaryModelRequest");
    expect(document.body).toContain("Return ONLY valid JSON. No explanations.");
    expect(document.body).toContain("Treat user-established facts and mutually visible outcomes as stronger evidence than unsupported assistant-only assumptions.");
    expect(document.body).toContain('"field": "supported.fieldPath"');
    expect(document.body).toContain("Examples are structural only. Do not copy example field paths");
    expect(document.body).toContain("RECENT CONVERSATION CONTEXT (for continuity and conflict checking only)");
    expect(document.body).toContain("EDGE VALIDATION NOTE");
    expect(document.body).toContain("evidence_not_in_latest_exchange");
    expect(document.body).not.toContain("RECENT CONVERSATION CONTEXT (for pattern detection)");
    expect(document.body).toContain("scenePosition: short factual snapshot of the character's immediate physical situation inside the current location");
    expect(document.body).toContain('"candidateReviews"');
    expect(document.body).toContain('"rejectedCandidates"');
    expect(document.body).toContain("BROWSER DEBUG ANNOTATIONS ADDED BEFORE STATE APPLICATION");
    expect(document.body).toContain('"characterUpdateReviews"');
    expect(document.body).toContain("SUPPORT CALL: GOAL PROGRESS EVALUATION");
    expect(document.body).toContain("/functions/v1/evaluate-goal-progress");
    expect(document.body).toContain('"temperature": 0.3');
    expect(document.body).toContain('"max_output_tokens": 1024');
    expect(document.body).toContain('"stepUpdates"');
	    expect(document.body).toContain('"classificationReviews"');
	    expect(document.body).toContain('"rejectedClassifications"');
	    expect(document.body).toContain('"chronicle_goal_progress"');
    expect(document.body).toContain("BROWSER DEBUG ANNOTATIONS ADDED BEFORE PERSISTENCE");
    expect(document.body).toContain("GOAL STEP DISCLOSURE NOTE");
    expect(document.body).toContain("The browser sends only the first incomplete milestone for each writer-visible story goal");
    expect(document.body).toContain('"stepCompletionReviews"');
    expect(document.body).toContain("SUPPORT CALL: GOAL ALIGNMENT EVALUATION");
    expect(document.body).toContain("/functions/v1/evaluate-goal-alignment");
    expect(document.body).toContain('"goals": [');
    expect(document.body).toContain('"openStep": "{{first open milestone description}}"');
	    expect(document.body).toContain("support|resistance|drift|neutral|not_applicable");
	    expect(document.body).toContain("these results may remain diagnostic until the app explicitly enables adaptive goal pressure");
	    expect(document.body).toContain('"chronicle_goal_alignment"');
	    expect(document.body).toContain('"alignmentReviews"');
	    expect(document.body).toContain('"rejectedEvaluations"');
	    expect(document.body).toContain("MEMORY EXTRACTION");
	    expect(document.body).toContain('"recentExistingMemories": ["{{up to 20 recent saved memory contents}}"]');
	    expect(document.body).toContain('"chronicle_memory_events"');
    const memorySectionStart = document.body.indexOf("MEMORY EXTRACTION");
    const memorySectionEnd = document.body.indexOf("DAY MEMORY COMPRESSION");
    expect(memorySectionStart).toBeGreaterThanOrEqual(0);
    expect(memorySectionEnd).toBeGreaterThan(memorySectionStart);
    const memorySection = document.body.slice(memorySectionStart, memorySectionEnd);
    expect(memorySection).toContain('"max_output_tokens": 1024');
	    expect(document.body).toContain("Review up to six candidates and accept at most three.");
	    expect(document.body).toContain("Only durable categories backed by raw user facts or accepted assistant observable changes may be accepted.");
	    expect(document.body).toContain("MEMORY OUTPUT CLEANUP NOTE");
	    expect(document.body).not.toContain("Keep each point under 90 characters.");
	    expect(document.body).not.toContain("Relationship milestones, intimacy milestones");
	    expect(document.body).toContain("Return ONLY JSON matching the requested schema.");
	    expect(document.body).toContain('"candidates"');
	    expect(document.body).toContain('"rejectedInputMemoryRows"');
    expect(document.body).toContain("RECENT SAVED MEMORIES:");
    expect(document.body).toContain("duplicates, repeated phrasing, and support artifacts remain rejected and inspectable");
    expect(document.body).toContain("DAY MEMORY COMPRESSION");
    expect(document.body).toContain("/functions/v1/compress-day-memories");
    expect(document.body).toContain('"inputMemoryRows": [{');
    expect(document.body).toContain('"compressedInputMemoryRowIds"');
    expect(document.body).toContain('"rejectedInputMemoryRows"');
    expect(document.body).toContain('"omittedInputMemoryRowIds"');
    expect(document.body).toContain('"inputTrustBoundary": "browser_supplied_runtime_rows"');
    expect(document.body).toContain("deletes only validated compressed row IDs");
    expect(document.body).not.toContain('"bullets": ["{{memory bullet from one day}}"]');
    expect(document.body).toContain('"max_output_tokens": 350');
    expect(document.body).toContain('"debugTrace": "{{true only when requested}}"');
    expect(document.body).toContain('"providerBodyError": "{{present only when provider returned a failed or malformed Responses body}}"');
    expect(document.body).toContain("OUTPUT CLEANUP NOTE");
    expect(document.body).toContain("SIDE-CHARACTER GENERATION");
    expect(document.body).toContain('"dialogContext": "{{first appearance dialogue that triggered discovery}}"');
    expect(document.body).toContain('"temperature": 0.55');
    expect(document.body).toContain("This helper lane remains on xAI Chat Completions in the current migration");
    expect(document.body).toContain('response_format.type = "json_schema"');
    expect(document.body).toContain('"response_format"');
    expect(document.body).toContain('"chronicle_side_character_profile"');
    expect(document.body).toContain("PROFILE SANITATION NOTE");
    expect(document.body).toContain("World context may shape public setting fit, but it does not prove private generated fields");
    expect(document.body).toContain("Empty generated nested fields do not overwrite existing extracted side-character details.");
    expect(document.body).toContain("Do not infer private sexuality, intimate anatomy, undergarments, secrets, fears, kinks, or hidden desires");
    expect(document.body).not.toContain('"temperature": 0.8');
    expect(document.body).not.toContain("a secret they might have");
    expect(document.body).toContain("SIDE-CHARACTER AVATAR PROMPT OPTIMIZATION");
    expect(document.body).toContain('"avatarPrompt": "{{source avatar prompt from side-character profile or character UI}}"');
    expect(document.body).toContain("used by the side-character portrait path and by other character/avatar UI surfaces");
    expect(document.body).toContain("CHARACTER FIELD ENHANCEMENT / AI FILL / AI GENERATE");
    expect(document.body).toContain("/functions/v1/chat with stream=false");
    expect(document.body).toContain('providerTransport="chat_completions"');
    expect(document.body).toContain("explicitly opt into the legacy xAI Chat Completions compatibility lane");
    expect(document.body).toContain("SECTION-SPECIFIC GUIDANCE MATRIX USED WHEN sectionHint MATCHES");
    expect(document.body).toContain("character tone/voice detail: Generate a tone/voice trait describing HOW this character speaks");
    expect(document.body).toContain("background detail: Generate an additional background detail");
    expect(document.body).toContain("STORY/WORLD FIELD ENHANCEMENT");
    expect(document.body).toContain("IMAGE GENERATION CALLS");
    expect(document.body).toContain("This section is only for scene and cover image generation.");
    expect(document.body).toContain('{ "role": "user|assistant", "text": "{{up to 5 recent roleplay messages used as visual context}}" }');
    expect(document.body).toContain("The edge function accepts either text or content");
    expect(document.body).toContain("visual-only current character appearance and outer-clothing summaries");
    expect(document.body).toContain("the browser sends only visual-safe character fields to this image lane");
    expect(document.body).toContain("SCENE IMAGE TEXT ANALYSIS REQUEST BODY SENT TO xAI");
    expect(document.body).toContain('"chronicle_scene_image_analysis"');
    expect(document.body).toContain("SCENE IMAGE NORMALIZATION NOTE");
    expect(document.body).toContain("Use weightedTraits sparingly.");
    expect(document.body).toContain("Do not infer private anatomy or identity from sparse cues.");
    expect(document.body).not.toContain("WEIGHTING RULES (MANDATORY)");
    expect(document.body).toContain('"prompt": "{{cover image source prompt}}"');
    expect(document.body).toContain("COVER IMAGE GENERATION REQUEST BODY SENT TO xAI");
    expect(document.body).not.toContain("{{eligible character cards only}}");
  });
});
