import { describe, expect, it } from "vitest";
import {
  apiInspectorPromptDocumentList,
  apiInspectorPromptDocuments,
  type ApiInspectorPromptDocumentId,
} from "./api-inspector-prompt-documents";

const requiredDocumentIds: ApiInspectorPromptDocumentId[] = ["api-call-1", "api-call-2-support"];

describe("api-inspector prompt document registry", () => {
  it("exposes exactly the two roleplay prompt review documents used by the header buttons", () => {
    expect(apiInspectorPromptDocumentList.map((document) => document.id)).toEqual(requiredDocumentIds);
    expect(Object.keys(apiInspectorPromptDocuments).sort()).toEqual([...requiredDocumentIds].sort());
  });

  it("keeps API Call 1 documented as source-backed current prompt text", () => {
    const document = apiInspectorPromptDocuments["api-call-1"];

    expect(document.buttonLabel).toBe("API Call 1");
    expect(document.body).toContain("FULL SYSTEM MESSAGE GENERATED BY getSystemInstruction()");
    expect(document.body).toContain("GROK REQUEST BODY SENT BY CHAT EDGE FUNCTION");
    expect(document.body).toContain('"temperature": 0.7');
    expect(document.body).toContain("{{up to 9 prior roleplay messages before the current turn}}");
    expect(document.body).toContain("{{adaptiveStyleDirective when triggered}}");
    expect(document.body).toContain("{{selectedResponseDetailRules}}");
    expect(document.body).toContain("{{responsePriorityCheck}}");
    expect(document.body).toContain("{{assistantStructureReminder}}");
    expect(document.body).toContain("SELECTED RESPONSE DETAIL RULES APPENDED TO FINAL USER MESSAGE ON EVERY LIVE ROLEPLAY CALL");
    expect(document.body).toContain("RESPONSE PRIORITY CHECK APPENDED TO FINAL USER MESSAGE ON EVERY LIVE ROLEPLAY CALL");
    expect(document.body).toContain("Write the next response from the immediate scene first.");
    expect(document.body).toContain("Do not surface background details, private traits, secrets, fears, kinks, goals, or backstory randomly.");
    expect(document.body).toContain("When the current beat directly activates one of those details through body contact, intimacy, exposure, secrecy, desire, fear, relationship tension, goal pressure, or another clear trigger");
    expect(document.body).toContain("ASSISTANT STRUCTURE REMINDER APPENDED TO FINAL USER MESSAGE ON EVERY LIVE ROLEPLAY CALL");
    expect(document.body).toContain("Compare against your own previous 2-3 assistant character blocks, not the user's message.");
    expect(document.body).toContain("--- SECTION 1 - CORE ROLE LOGIC ---");
    expect(document.body).toContain("--- SECTION 7 - DIALOG FORMATTING AND ROLEPLAY RULES ---");
    expect(document.body).toContain("REGENERATION REQUEST APPENDED TO FINAL USER MESSAGE ONLY WHEN REGENERATING");
    expect(document.body).toContain("CONTINUE REQUEST FINAL USER MESSAGE ONLY WHEN PRESSING CONTINUE");
    expect(document.body).toContain("--- SECTION 8 - CHAT SETTINGS PER USER PREFERENCE ---");
    expect(document.body).toContain("This review document shows every possible chat-setting injection branch grouped under its setting.");
    expect(document.body).toContain("A real API Call 1 request sends only one branch per group based on the user's current chat settings.");
    expect(document.body).toContain("NARRATIVE POV: First Person");
    expect(document.body).toContain("NARRATIVE POV: Third Person");
    expect(document.body).toContain("// Sent when Character Discovery = Proactive / On");
    expect(document.body).toContain("// Sent when Character Discovery = Strict / Off");
    expect(document.body).toContain("// Sent when Proactive AI Mode = On");
    expect(document.body).toContain("// Sent when Proactive AI Mode = Off");
    expect(document.body).toContain("NSFW INTENSITY: Normal");
    expect(document.body).toContain("NSFW INTENSITY: High");
    expect(document.body).not.toContain("NSFW INTENSITY: Natural");
    expect(document.body).toContain("RESPONSE DETAIL: Concise");
    expect(document.body).toContain("REQUEST max_tokens: 1024");
    expect(document.body).toContain("RESPONSE DETAIL: Balanced");
    expect(document.body).toContain("REQUEST max_tokens: 2048");
    expect(document.body).toContain("RESPONSE DETAIL: Detailed");
    expect(document.body).toContain("REQUEST max_tokens: 3072");
    expect(document.body).toContain("REALISM MODE: Off");
    expect(document.body).toContain("REALISM MODE: On");
    expect(document.body).not.toContain("{{first-person branch text}}");
    expect(document.body).not.toContain("not a literal payload dump");
  });

  it("covers API Call 2 support lanes with current prompt bodies", () => {
    const document = apiInspectorPromptDocuments["api-call-2-support"];

    expect(document.buttonLabel).toBe("API Call 2 + Support Calls");
    expect(document.body).toContain("API CALL 2: CHARACTER STATE SYNC");
    expect(document.body).toContain("Return ONLY valid JSON. No explanations.");
    expect(document.body).toContain("scenePosition: volatile immediate placement within the broad place");
    expect(document.body).toContain("SUPPORT CALL: GOAL ALIGNMENT EVALUATION");
    expect(document.body).toContain("/functions/v1/evaluate-goal-alignment");
    expect(document.body).toContain("support|resistance|drift|neutral|not_applicable");
    expect(document.body).toContain("the app code will apply different scoring rates later");
    expect(document.body).toContain("MEMORY EXTRACTION");
    expect(document.body).toContain("SIDE-CHARACTER GENERATION");
    expect(document.body).toContain("SIDE-CHARACTER AVATAR PROMPT OPTIMIZATION");
    expect(document.body).toContain("This section is only for the side-character portrait path.");
    expect(document.body).toContain("CHARACTER FIELD ENHANCEMENT / AI FILL / AI GENERATE");
    expect(document.body).toContain("STORY/WORLD FIELD ENHANCEMENT");
    expect(document.body).toContain("IMAGE GENERATION CALLS");
    expect(document.body).toContain("This section is only for scene and cover image generation.");
    expect(document.body).not.toContain("{{eligible character cards only}}");
  });
});
